/**
 * LuckyMaze.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MazeCell } from './mazeCell';
import { MazeExit } from './mazeExit';


export interface ActiveGameDetailsDto { 
    state?: string | null;
    timerSeconds?: number;
    width?: number | null;
    height?: number | null;
    gridData?: Array<MazeCell> | null;
    exits?: Array<MazeExit> | null;
}

