/**
 * LuckyMaze.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameState } from './gameState';


export interface GameHistoryDto { 
    id?: string;
    state?: GameState;
    winningExit?: string | null;
    startedAt?: string | null;
    endedAt?: string | null;
}
export namespace GameHistoryDto {
}


