/**
 * LuckyMaze.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GameState = {
    Idle: 'Idle',
    Countdown: 'Countdown',
    Betting: 'Betting',
    Starting: 'Starting',
    Playing: 'Playing',
    Finished: 'Finished'
} as const;
export type GameState = typeof GameState[keyof typeof GameState];

