/**
 * LuckyMaze.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MazeSize } from './mazeSize';


export interface GameSettings { 
    id?: string;
    createdAt?: string;
    updatedAt?: string;
    mazeSize?: MazeSize;
    gameSpeedMs?: number;
    minBet?: number;
    maxBet?: number;
}
export namespace GameSettings {
}


