/**
 * LuckyMaze.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MazeCell { 
    x?: number;
    y?: number;
    north?: boolean;
    east?: boolean;
    south?: boolean;
    west?: boolean;
}

