/**
 * LuckyMaze.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const NetworkMode = {
    Wifi: 'Wifi',
    Hotspot: 'Hotspot'
} as const;
export type NetworkMode = typeof NetworkMode[keyof typeof NetworkMode];

