/**
 * LuckyMaze.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NetworkMode } from './networkMode';


export interface NetworkModeRequest { 
    mode?: NetworkMode;
    permanent?: boolean;
}
export namespace NetworkModeRequest {
}


